const VIDEO_PLAYLIST = [
  {
    id: "1",
    title: "Big Buck Bunny",
    subtitle: "Blender Foundation",
    description: "Big Buck Bunny sample video.",
    videoUrl:
      "https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_1MB.mp4",
    thumb: "https://picsum.photos/640/360?random=1",
  },
  {
    id: "2",
    title: "Elephants Dream",
    subtitle: "Blender Foundation",
    description: "Elephants Dream sample video.",
    videoUrl: "https://archive.org/download/ElephantsDream/ed_1024_512kb.mp4",
    thumb: "https://picsum.photos/640/360?random=2",
  },
  {
    id: "5",
    title: "Sample Video 5s",
    subtitle: "SampleLib",
    description: "5 second MP4 sample.",
    videoUrl: "https://samplelib.com/lib/preview/mp4/sample-5s.mp4",
    thumb: "https://picsum.photos/640/360?random=5",
  },
  {
    id: "6",
    title: "Sample Video 10s",
    subtitle: "SampleLib",
    description: "10 second MP4 sample.",
    videoUrl: "https://samplelib.com/lib/preview/mp4/sample-10s.mp4",
    thumb: "https://picsum.photos/640/360?random=6",
  },
  {
    id: "9",
    title: "Ocean Sample",
    subtitle: "FileSamples",
    description: "Ocean video sample.",
    videoUrl:
      "https://filesamples.com/samples/video/mp4/sample_960x400_ocean_with_audio.mp4",
    thumb: "https://picsum.photos/640/360?random=9",
  },
  {
    id: "10",
    title: "640x360 Sample",
    subtitle: "FileSamples",
    description: "MP4 sample.",
    videoUrl: "https://filesamples.com/samples/video/mp4/sample_640x360.mp4",
    thumb: "https://picsum.photos/640/360?random=10",
  },
  {
    id: "11",
    title: "1 MB Sample",
    subtitle: "TrueFileSize",
    description: "1 MB MP4.",
    videoUrl: "https://cdn.truefilesize.com/mp4/sample-1mb.mp4",
    thumb: "https://picsum.photos/640/360?random=11",
  },
  {
    id: "12",
    title: "5 MB Sample",
    subtitle: "TrueFileSize",
    description: "5 MB MP4.",
    videoUrl: "https://cdn.truefilesize.com/mp4/sample-5mb.mp4",
    thumb: "https://picsum.photos/640/360?random=12",
  },
  {
    description:
      "The Smoking Tire meets up with Chris and Jorge from CarsForAGrand.com to see just how far $1,000 can go when looking for a car...",
    videoUrl: "https://media.w3.org/2010/05/video/movie_300.mp4",
    subtitle: "By Garage419",
    thumb: "https://media.w3.org/2010/05/video/poster.png",
    title: "What care can you get for a grand?",
    id: "123464",
  },
  {
    description:
      "Smoking Tire takes the all-new Subaru Outback to the highest point we can find in hopes our customer-appreciation Balloon Launch will get some free T-shirts into the hands of our viewers.",
    videoUrl: "https://media.w3.org/2010/05/sintel/trailer.mp4",
    subtitle: "By Garage419",
    thumb: "https://media.w3.org/2010/05/sintel/poster.png",
    title: "Subaru Outback On Street And Dirt",
    id: "123460",
  },
  {
    id: "18",
    title: "Short Clip",
    subtitle: "Demo",
    description: "Short sample video.",
    videoUrl: "https://samplelib.com/lib/preview/mp4/sample-20s.mp4",
    thumb: "https://picsum.photos/640/360?random=18",
  },
  {
    id: "19",
    title: "Demo Clip",
    subtitle: "Demo",
    description: "Another MP4 sample.",
    videoUrl: "https://samplelib.com/lib/preview/mp4/sample-10s.mp4",
    thumb: "https://picsum.photos/640/360?random=19",
  },
  {
    id: "20",
    title: "Trailer",
    subtitle: "Demo",
    description: "Trailer sample.",
    videoUrl: "https://samplelib.com/lib/preview/mp4/sample-5s.mp4",
    thumb: "https://picsum.photos/640/360?random=20",
  },
];

export default VIDEO_PLAYLIST;
